### ISSUE TITLE
Pull macro for Lightning Lure/grasping vine

### ISSUE THREAD

**Issue by Avera9eJoe** [theripper93/FoundryVTT-Macros#2]
The knockback and thunderwave macros are both incredibly useful for automating combat, especially when tied with a simple `if (!args[0].failedSaves.length) return;` line added at the top to only and automatically execute when the target fails their save.

However, setting the knockback distance to something negative, for if you wanted to pull a target towards you instead of away which is the case with Lightning Lure/Grasping Vine and a few other spells, seems to break the mathematics involved. Would it be possible for you to release a "pull" variant of the knockback macro? I.E. "Pull target 15ft closer, and stop pulling if they are directly adjacent."

**Comment by theripper93** [comment]
I no longer work on macros, this is just an old repository
